version: '2'
services:
  etl_data_pipeline:
    build:
      context: .
      dockerfile: ./etl_data_pipeline/Dockerfile
    command: python ./etl_data_pipeline/main.py
    ports:
      - "5000:5000"
    volumes:
      - .:/etl_data_pipeline
    networks:
      - python-network

  data_storage:
    build:
      context: .
      dockerfile: ./data_storage/Dockerfile
    command: python ./data_storage/main.py
    restart: always
    depends_on:
      - db
      - init-kafka
    ports:
      - "5001:5001"
    volumes:
      - .:/data_storage
    links:
      - db
    networks:
      - python-network


  data_retrieval:
    build:
      context: .
      dockerfile: ./data_retrieval/Dockerfile
    command: python ./data_retrieval/main.py
    restart: always
    depends_on:
      - db
    ports:
      - "5002:5002"
    volumes:
      - .:/data_retrieval
    networks:
      - python-network

  sla_manager:
    build:
      context: .
      dockerfile: sla_manager/Dockerfile
    command: python ./sla_manager/main.py
    ports:
      - "5003:5003"
    volumes:
      - .:/sla_manager
    networks:
      - python-network



  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - python-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - python-network

  init-kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:29092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic promethuesdata --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:29092 --list
      "
    networks:
      - python-network

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "asdf.VHjI.313"
    ports:
      - "3306:3306"
    networks:
      - python-network

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    networks:
      - python-network

networks:
  python-network:
    driver: bridge